# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cjy/riscv_simulator/riscv_5stage_simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cjy/riscv_simulator/riscv_5stage_simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cjy/riscv_simulator/riscv_5stage_simulator/CMakeFiles /home/cjy/riscv_simulator/riscv_5stage_simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cjy/riscv_simulator/riscv_5stage_simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named riscv_simulator.out

# Build rule for target.
riscv_simulator.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 riscv_simulator.out
.PHONY : riscv_simulator.out

# fast build rule for target.
riscv_simulator.out/fast:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/build
.PHONY : riscv_simulator.out/fast

elf.o: elf.cpp.o

.PHONY : elf.o

# target to build an object file
elf.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/elf.cpp.o
.PHONY : elf.cpp.o

elf.i: elf.cpp.i

.PHONY : elf.i

# target to preprocess a source file
elf.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/elf.cpp.i
.PHONY : elf.cpp.i

elf.s: elf.cpp.s

.PHONY : elf.s

# target to generate assembly for a file
elf.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/elf.cpp.s
.PHONY : elf.cpp.s

instruction.o: instruction.cpp.o

.PHONY : instruction.o

# target to build an object file
instruction.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/instruction.cpp.o
.PHONY : instruction.cpp.o

instruction.i: instruction.cpp.i

.PHONY : instruction.i

# target to preprocess a source file
instruction.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/instruction.cpp.i
.PHONY : instruction.cpp.i

instruction.s: instruction.cpp.s

.PHONY : instruction.s

# target to generate assembly for a file
instruction.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/instruction.cpp.s
.PHONY : instruction.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/main.cpp.s
.PHONY : main.cpp.s

memory.o: memory.cpp.o

.PHONY : memory.o

# target to build an object file
memory.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/memory.cpp.o
.PHONY : memory.cpp.o

memory.i: memory.cpp.i

.PHONY : memory.i

# target to preprocess a source file
memory.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/memory.cpp.i
.PHONY : memory.cpp.i

memory.s: memory.cpp.s

.PHONY : memory.s

# target to generate assembly for a file
memory.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/memory.cpp.s
.PHONY : memory.cpp.s

pipeline.o: pipeline.cpp.o

.PHONY : pipeline.o

# target to build an object file
pipeline.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/pipeline.cpp.o
.PHONY : pipeline.cpp.o

pipeline.i: pipeline.cpp.i

.PHONY : pipeline.i

# target to preprocess a source file
pipeline.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/pipeline.cpp.i
.PHONY : pipeline.cpp.i

pipeline.s: pipeline.cpp.s

.PHONY : pipeline.s

# target to generate assembly for a file
pipeline.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/pipeline.cpp.s
.PHONY : pipeline.cpp.s

syscall.o: syscall.cpp.o

.PHONY : syscall.o

# target to build an object file
syscall.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/syscall.cpp.o
.PHONY : syscall.cpp.o

syscall.i: syscall.cpp.i

.PHONY : syscall.i

# target to preprocess a source file
syscall.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/syscall.cpp.i
.PHONY : syscall.cpp.i

syscall.s: syscall.cpp.s

.PHONY : syscall.s

# target to generate assembly for a file
syscall.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/syscall.cpp.s
.PHONY : syscall.cpp.s

tomasulo.o: tomasulo.cpp.o

.PHONY : tomasulo.o

# target to build an object file
tomasulo.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/tomasulo.cpp.o
.PHONY : tomasulo.cpp.o

tomasulo.i: tomasulo.cpp.i

.PHONY : tomasulo.i

# target to preprocess a source file
tomasulo.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/tomasulo.cpp.i
.PHONY : tomasulo.cpp.i

tomasulo.s: tomasulo.cpp.s

.PHONY : tomasulo.s

# target to generate assembly for a file
tomasulo.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/tomasulo.cpp.s
.PHONY : tomasulo.cpp.s

tomasulo_2.o: tomasulo_2.cpp.o

.PHONY : tomasulo_2.o

# target to build an object file
tomasulo_2.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/tomasulo_2.cpp.o
.PHONY : tomasulo_2.cpp.o

tomasulo_2.i: tomasulo_2.cpp.i

.PHONY : tomasulo_2.i

# target to preprocess a source file
tomasulo_2.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/tomasulo_2.cpp.i
.PHONY : tomasulo_2.cpp.i

tomasulo_2.s: tomasulo_2.cpp.s

.PHONY : tomasulo_2.s

# target to generate assembly for a file
tomasulo_2.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_simulator.out.dir/build.make CMakeFiles/riscv_simulator.out.dir/tomasulo_2.cpp.s
.PHONY : tomasulo_2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... riscv_simulator.out"
	@echo "... edit_cache"
	@echo "... elf.o"
	@echo "... elf.i"
	@echo "... elf.s"
	@echo "... instruction.o"
	@echo "... instruction.i"
	@echo "... instruction.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... pipeline.o"
	@echo "... pipeline.i"
	@echo "... pipeline.s"
	@echo "... syscall.o"
	@echo "... syscall.i"
	@echo "... syscall.s"
	@echo "... tomasulo.o"
	@echo "... tomasulo.i"
	@echo "... tomasulo.s"
	@echo "... tomasulo_2.o"
	@echo "... tomasulo_2.i"
	@echo "... tomasulo_2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

